version: '3.8'

services:
  mysql-db:
    container_name: mysql-db
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - mysql-volume:/var/lib/mysql:rw
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  nestjs-app:
    container_name: nestjs-app
    depends_on:
      - mysql-db
    build:
      context: ../
      dockerfile: docker/dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NESTJS_APP_LOCAL_PORT:$NESTJS_APP_DOCKER_PORT
    environment:
      DB_HOST: mysql-db
      DB_USER: $MYSQLDB_USER
      DB_PASS: $MYSQLDB_PASSWORD
      DB_NAME: $MYSQLDB_DATABASE
      DB_PORT: $MYSQLDB_DOCKER_PORT
    volumes:
      - ../:/app
      - /app/node_modules

volumes:
  mysql-volume:
